apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drcid98/odoo-app.git
    targetRevision: main
    path: k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: odoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true